name: Add Comment to Dependabot PR

on:
  pull_request:
    paths:
      - 'pom.xml'

jobs:
  add-comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: install xmllint
        run: |
          sudo apt-get install -y libxml2-utils

      - uses: actions/checkout@v4
        with:
          ref: main
          path: main
          sparse-checkout: |
            pom.xml
          sparse-checkout-cone-mode: false

      - uses: actions/checkout@v4
        with:
          path: pr
          sparse-checkout: |
            pom.xml
          sparse-checkout-cone-mode: false

      - name: parse jenkins version from PR pom.xml
        id: jenkins_version
        run: |
          echo "JENKINS_VERSION=$(xmllint --xpath '//*[name() = "parent"]/*[name() = "version"]/text()' pr/pom.xml)" >> "$GITHUB_ENV"

      - name: parse jenkins version from main branch
        id: last_jenkins_version
        run: |
          echo "LAST_JENKINS_VERSION=$(xmllint --xpath '//*[name() = "parent"]/*[name() = "version"]/text()' main/pom.xml)" >> "$GITHUB_ENV"

      - name: Print the versions
        id: step_three
        run: |
          printf '%s\n' "$JENKINS_VERSION" "$LAST_JENKINS_VERSION"

      - name: Add Comment to PR
        if: env.JENKINS_VERSION != env.LAST_JENKINS_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT: "When updating `jenkins-plugins`, please manually update the dynamic preview environment `cloudbees-core-cm` version in [`preview/Dockerfile`](https://github.com/cloudbees/cloudbees-pipeline-explorer-plugin/blob/main/preview/Dockerfile#L1) to match the upstream version from `jenkins-plugins` before merging the PR."
        run: |
          gh issue comment ${{ github.event.pull_request.number }} --repo "$GITHUB_REPOSITORY" --body "$COMMENT"
